# Generated by Django 4.2 on 2025-09-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialApplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
